name: Build and Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: |
        rm -rf ./dist
        npm run build

    - name: Publish Website
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: 'dist'
        single-commit: true
